import { cpSync, existsSync, readFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildXDC } from '@webxdc/vite-plugins';
import { build, defineConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';

// 'hq' (default): ship the canonical sources as-is — bit-exact lossless
// cartoon-art pixels.  'casual': ship the pre-quantized counterparts
// committed at img-casual/ and icon-casual.png (regenerated by
// `pnpm quantize-assets`), trading visually-imperceptible 256-color
// quantization for a ~60% smaller .xdc.  See README.md "Bundle variants".
const variant = process.env.BUILD_VARIANT || 'hq';
if (variant !== 'hq' && variant !== 'casual') {
  throw new Error(`BUILD_VARIANT must be 'hq' or 'casual', got '${variant}'`);
}

// Release builds (CI tag pipeline) set BUILD_RELEASE=1 to drop sourcemaps
// from the .xdc.  Dev/test builds keep sourcemaps so a tester loading the
// .xdc into Delta Chat can debug against the original sources.
const isRelease = process.env.BUILD_RELEASE === '1';

// Plugin: for the casual variant, after vite-plugin-static-copy has run,
// replace the canonical dist/img/ + dist/icon.png with the pre-quantized
// counterparts (img-casual/, icon-casual.png).  This keeps the in-bundle
// paths variant-independent (`img/sprite-XXX.png`, `icon.png`) so ruleset
// frameSrc strings and manifest.toml's `icon = "icon.png"` work uniformly.
//
// Order in plugins[] matters: this must run AFTER viteStaticCopy (so
// dist/img/ exists from the unconditional `{ src: 'img', dest: '' }`
// target) and BEFORE buildXDC zips dist/.  Vite runs `closeBundle` hooks
// in plugin-array declaration order.
function swapInCasualAssets() {
  return {
    name: 'swap-in-casual-assets',
    apply: 'build',
    closeBundle() {
      if (variant !== 'casual') return;
      const root = fileURLToPath(new URL('.', import.meta.url));
      const distImg = `${root}dist/img`;
      const distIcon = `${root}dist/icon.png`;
      const srcImg = `${root}img-casual`;
      const srcIcon = `${root}icon-casual.png`;
      if (!existsSync(srcImg) || !existsSync(srcIcon)) {
        throw new Error(
          `[swap-in-casual-assets] missing pre-quantized assets at ${srcImg} / ${srcIcon}. ` +
            'Run `pnpm quantize-assets` to (re)generate them.'
        );
      }
      rmSync(distImg, { recursive: true, force: true });
      cpSync(srcImg, distImg, { recursive: true });
      rmSync(distIcon, { force: true });
      cpSync(srcIcon, distIcon);
      console.log(
        '[swap-in-casual-assets] dist/img/ and dist/icon.png replaced with casual variants'
      );
    },
  };
}

// Serve the @webxdc/vite-plugins simulator with an explicit Content-Type so
// strict-MIME environments (GitHub Codespaces reverse proxy) don't block it.
function mockWebxdc() {
  const src = readFileSync(
    fileURLToPath(new URL('./node_modules/@webxdc/vite-plugins/src/webxdc.js', import.meta.url)),
    'utf-8'
  );
  return {
    name: 'webxdc-mock',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url === '/webxdc.js') {
          res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
          res.end(src);
        } else {
          next();
        }
      });
    },
  };
}

// In dev (`vite`), `scripts/esm-bundle.js` doesn't exist as a source
// file — it is only produced by `vite build`.  Index.html references
// it as a `<script>` tag, so this plugin runs the same Rollup pipeline
// the prod build uses, in-memory, and serves the result via middleware.
function bundleEsmDev() {
  let bundleSrc = null;
  let buildPromise = null;

  function rebuild() {
    if (buildPromise) return buildPromise;
    buildPromise = (async () => {
      try {
        const result = await build({
          configFile: false,
          root: process.cwd(),
          logLevel: 'error',
          build: {
            write: false,
            emptyOutDir: false,
            rollupOptions: {
              input: 'scripts/esm-entry.js',
              output: {
                format: 'iife',
                name: '__DD',
                entryFileNames: 'esm-bundle.js',
              },
            },
          },
        });
        const out = (Array.isArray(result) ? result[0] : result).output.find(
          (o) => o.fileName === 'esm-bundle.js'
        );
        bundleSrc = out ? out.code : null;
      } finally {
        buildPromise = null;
      }
    })();
    return buildPromise;
  }

  return {
    name: 'esm-bundle-dev',
    apply: 'serve',
    async configureServer(server) {
      // Kick off the initial build but don't block listen() on it —
      // the middleware below returns 503 until bundleSrc is set, and
      // the browser will pick up the bundle on its next request.
      rebuild().catch((err) => {
        server.config.logger.error('[esm-bundle-dev] initial build failed: ' + err.message);
      });
      server.watcher.on('change', (file) => {
        if (file.includes('/scripts/') && (file.endsWith('.js') || file.endsWith('.ts'))) {
          rebuild().catch((err) => {
            server.config.logger.error('[esm-bundle-dev] rebuild failed: ' + err.message);
          });
        }
      });
      server.middlewares.use(async (req, res, next) => {
        if (req.url === '/scripts/esm-bundle.js' || req.url === '/scripts/esm-bundle.js?') {
          // First request after server start may race with the initial
          // Rollup build kicked off in configureServer.  Await the
          // in-flight build (or start one) instead of 503-ing — the
          // browser's `<script defer>` tag does not auto-retry, so a
          // 503 here would leave the page silently stuck on the loader.
          if (!bundleSrc) {
            try {
              await (buildPromise || rebuild());
            } catch (err) {
              server.config.logger.error('[esm-bundle-dev] build failed: ' + err.message);
            }
          }
          if (!bundleSrc) {
            res.statusCode = 503;
            res.end('// esm-bundle build failed; see vite logs');
            return;
          }
          res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
          res.end(bundleSrc);
          return;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  root: '.',
  publicDir: false,

  server: {
    port: 3000,
    open: false,
  },

  preview: {
    port: 3000,
  },

  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // Tree-shaking and minification (esbuild) come for free from Rollup
    // + Vite defaults — set them explicitly so the .xdc artifact never
    // accidentally regresses to an unminified bundle if a future Vite
    // major flips a default.
    minify: 'esbuild',
    // Sourcemaps in dev/test (.xdc files attached to PRs); stripped from
    // release artifacts to keep tag-built .xdc bytes lean and avoid
    // shipping original-source paths to end users.  Gated via
    // BUILD_RELEASE=1 (set by .github/workflows/test.yml on tag builds).
    sourcemap: !isRelease,
    // Default is 4096; pin it so the threshold for inlining small icons
    // / fonts vs. shipping them as separate dist/ files is visible in
    // config rather than implicit in Vite version bumps.
    assetsInlineLimit: 4096,
    // Vite's default 500 kB warning fires noisily on every build at the
    // current ~1.1 MB minified bundle.  webxdc apps load once from local
    // storage; HTTP-request elimination via code-splitting wouldn't help
    // (every chunk just becomes another file inside the .xdc).  See #192
    // "Out of scope".  Raise the threshold to 1500 kB so the warning
    // resurfaces only if the bundle grows past where re-evaluating the
    // single-chunk decision actually makes sense.
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      input: 'scripts/esm-entry.js',
      output: {
        format: 'iife',
        name: '__DD',
        entryFileNames: 'scripts/esm-bundle.js',
      },
    },
  },

  plugins: [
    mockWebxdc(),
    bundleEsmDev(),
    viteStaticCopy({
      targets: [
        { src: 'index.html', dest: '' },
        { src: 'manifest.toml', dest: '' },
        { src: 'icon.png', dest: '' },
        { src: 'CREDITS.txt', dest: '' },
        { src: 'LICENSE.txt', dest: '' },
        { src: 'LICENSE-CODE.txt', dest: '' },
        { src: 'LICENSE-ASSETS.txt', dest: '' },
        // Vendor libs are loaded as plain `<script>` tags from index.html
        // and exposed as browser globals (window.jQuery, window._, …)
        // the ESM bundle reads from globalThis.
        { src: 'vendor', dest: '' },
        { src: 'css', dest: '' },
        { src: 'img', dest: '' },
        // Ship only the fonts referenced from CSS; BowlbyOne.ttf and
        // BowlbyOneSC.ttf are unused (the .woff is loaded instead).
        { src: 'font/BowlbyOneSC.woff', dest: '' },
        { src: 'font/Voltaire-Regular.ttf', dest: '' },
        { src: 'font/Skranji-Regular.ttf', dest: '' },
        { src: 'font/SourceSansPro-Black.woff', dest: '' },
        { src: 'font/LICENSE', dest: '' },
        // views/*.html templates are now `?raw`-imported and bundled
        // into esm-bundle.js; the directory itself is no longer shipped.
        { src: 'data', dest: '' },
        { src: 'i18n', dest: '' },
      ],
    }),
    swapInCasualAssets(),
    buildXDC({ inDir: 'dist', outDir: '.', outFileName: `data-dealer-${variant}.xdc` }),
  ],
});
