import {
  cpSync,
  existsSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildXDC } from '@webxdc/vite-plugins';
import { build, defineConfig, transformWithEsbuild } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';

// 'hq' (default): ship the canonical sources as-is — bit-exact lossless
// cartoon-art pixels.  'casual': ship the pre-quantized counterparts
// committed at img-casual/ and icon-casual.png (regenerated by
// `pnpm quantize-assets`), trading visually-imperceptible 256-color
// quantization for a ~60% smaller .xdc.  See README.md "Bundle variants".
const variant = process.env.BUILD_VARIANT || 'hq';
if (variant !== 'hq' && variant !== 'casual') {
  throw new Error(`BUILD_VARIANT must be 'hq' or 'casual', got '${variant}'`);
}

// Release builds (CI tag pipeline) set BUILD_RELEASE=1 to drop sourcemaps
// from the .xdc.  Dev/test builds keep sourcemaps so a tester loading the
// .xdc into Delta Chat can debug against the original sources.
const isRelease = process.env.BUILD_RELEASE === '1';

// Plugin: for the casual variant, after vite-plugin-static-copy has run,
// replace the canonical dist/img/ + dist/icon.png with the pre-quantized
// counterparts (img-casual/, icon-casual.png).  This keeps the in-bundle
// paths variant-independent (`img/sprite-XXX.png`, `icon.png`) so ruleset
// frameSrc strings and manifest.toml's `icon = "icon.png"` work uniformly.
//
// Order in plugins[] matters: this must run AFTER viteStaticCopy (so
// dist/img/ exists from the unconditional `{ src: 'img', dest: '' }`
// target) and BEFORE buildXDC zips dist/.  Vite runs `closeBundle` hooks
// in plugin-array declaration order.
function swapInCasualAssets() {
  return {
    name: 'swap-in-casual-assets',
    apply: 'build',
    closeBundle() {
      if (variant !== 'casual') return;
      const root = fileURLToPath(new URL('.', import.meta.url));
      const distImg = `${root}dist/img`;
      const distIcon = `${root}dist/icon.png`;
      const srcImg = `${root}img-casual`;
      const srcIcon = `${root}icon-casual.png`;
      if (!existsSync(srcImg) || !existsSync(srcIcon)) {
        throw new Error(
          `[swap-in-casual-assets] missing pre-quantized assets at ${srcImg} / ${srcIcon}. ` +
            'Run `pnpm quantize-assets` to (re)generate them.'
        );
      }
      rmSync(distImg, { recursive: true, force: true });
      cpSync(srcImg, distImg, { recursive: true });
      rmSync(distIcon, { force: true });
      cpSync(srcIcon, distIcon);
      console.log(
        '[swap-in-casual-assets] dist/img/ and dist/icon.png replaced with casual variants'
      );
    },
  };
}

// Strip whitespace from runtime-loaded JSON (rulesets in data/, locale
// catalogs in i18n/).  These files are copied verbatim by
// vite-plugin-static-copy from the source-tree pretty-printed originals;
// inside the .xdc the indentation is dead bytes — JSON.parse / stringify
// cuts ~38% (1.24 MB → 770 kB on the current ruleset corpus) with no
// runtime semantics change.
//
// Order in plugins[] matters: this must run AFTER viteStaticCopy (so
// the files exist in dist/) and BEFORE buildXDC zips dist/.
function minifyStaticJson() {
  const targets = ['dist/data', 'dist/i18n'];
  const root = fileURLToPath(new URL('.', import.meta.url));

  function walkJson(dir) {
    const out = [];
    for (const name of readdirSync(dir)) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) out.push(...walkJson(full));
      else if (name.endsWith('.json')) out.push(full);
    }
    return out;
  }

  return {
    name: 'minify-static-json',
    apply: 'build',
    closeBundle() {
      let totalSaved = 0;
      let fileCount = 0;
      for (const rel of targets) {
        const dir = join(root, rel);
        if (!existsSync(dir)) continue;
        for (const f of walkJson(dir)) {
          const original = readFileSync(f, 'utf-8');
          // Re-stringify without whitespace.  Throws on malformed JSON
          // — we want that: a bad ruleset should fail the build, not
          // silently ship.
          const compact = JSON.stringify(JSON.parse(original));
          if (compact.length < original.length) {
            writeFileSync(f, compact);
            totalSaved += original.length - compact.length;
            fileCount++;
          }
        }
      }
      if (fileCount > 0) {
        const kb = (totalSaved / 1024).toFixed(1);
        console.log(
          `[minify-static-json] compacted ${fileCount} file${fileCount === 1 ? '' : 's'}, saved ${kb} kB`
        );
      }
    },
  };
}

// vite-plugin-static-copy `transform` callback: minify CSS via Vite's
// re-exported esbuild.  Each of dd.css / Render.css / Statusbar.css /
// MainMenu.css is rewritten in place; the four files stay separate so
// the existing `<link>` cascade order in index.html keeps working
// without index.html or scripts/esm-entry.ts changes.  Bundling the
// four into a single style.[hash].css would save another ~2 kB of
// per-file overhead but force an index.html rewrite — out of scope.
async function minifyCssTransform(src) {
  const text = typeof src === 'string' ? src : src.toString('utf-8');
  const result = await transformWithEsbuild(text, 'inline.css', {
    loader: 'css',
    minify: true,
  });
  return result.code;
}

// Serve the @webxdc/vite-plugins simulator with an explicit Content-Type so
// strict-MIME environments (GitHub Codespaces reverse proxy) don't block it.
function mockWebxdc() {
  const src = readFileSync(
    fileURLToPath(new URL('./node_modules/@webxdc/vite-plugins/src/webxdc.js', import.meta.url)),
    'utf-8'
  );
  return {
    name: 'webxdc-mock',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url === '/webxdc.js') {
          res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
          res.end(src);
        } else {
          next();
        }
      });
    },
  };
}

// In dev (`vite`), `scripts/esm-bundle.js` doesn't exist as a source
// file — it is only produced by `vite build`.  Index.html references
// it as a `<script>` tag, so this plugin runs the same Rollup pipeline
// the prod build uses, in-memory, and serves the result via middleware.
function bundleEsmDev() {
  let bundleSrc = null;
  let buildPromise = null;

  function rebuild() {
    if (buildPromise) return buildPromise;
    buildPromise = (async () => {
      try {
        const result = await build({
          configFile: false,
          root: process.cwd(),
          logLevel: 'error',
          esbuild: {
            jsx: 'automatic',
            jsxImportSource: 'preact',
          },
          build: {
            write: false,
            emptyOutDir: false,
            rollupOptions: {
              input: 'scripts/esm-entry.js',
              output: {
                format: 'iife',
                name: '__DD',
                entryFileNames: 'esm-bundle.js',
              },
            },
          },
        });
        // `result` is RolldownOutput | RolldownWatcher in Vite 8's types; we
        // never pass `watch`, so it's always the output shape — cast through
        // `any` so checkJs accepts the `.output` access without taking a hard
        // dep on the Rolldown types (transitive, not in package.json).
        const settled = /** @type {{ output: { fileName: string, code?: string }[] }} */ (
          /** @type {any} */ (Array.isArray(result) ? result[0] : result)
        );
        const out = settled.output.find((o) => o.fileName === 'esm-bundle.js');
        bundleSrc = out ? out.code : null;
      } finally {
        buildPromise = null;
      }
    })();
    return buildPromise;
  }

  return {
    name: 'esm-bundle-dev',
    apply: 'serve',
    async configureServer(server) {
      // Kick off the initial build but don't block listen() on it —
      // the middleware below returns 503 until bundleSrc is set, and
      // the browser will pick up the bundle on its next request.
      rebuild().catch((err) => {
        server.config.logger.error('[esm-bundle-dev] initial build failed: ' + err.message);
      });
      server.watcher.on('change', (file) => {
        if (file.includes('/scripts/') && (file.endsWith('.js') || file.endsWith('.ts'))) {
          rebuild().catch((err) => {
            server.config.logger.error('[esm-bundle-dev] rebuild failed: ' + err.message);
          });
        }
      });
      server.middlewares.use(async (req, res, next) => {
        if (req.url === '/scripts/esm-bundle.js' || req.url === '/scripts/esm-bundle.js?') {
          // First request after server start may race with the initial
          // Rollup build kicked off in configureServer.  Await the
          // in-flight build (or start one) instead of 503-ing — the
          // browser's `<script defer>` tag does not auto-retry, so a
          // 503 here would leave the page silently stuck on the loader.
          if (!bundleSrc) {
            try {
              await (buildPromise || rebuild());
            } catch (err) {
              server.config.logger.error('[esm-bundle-dev] build failed: ' + err.message);
            }
          }
          if (!bundleSrc) {
            res.statusCode = 503;
            res.end('// esm-bundle build failed; see vite logs');
            return;
          }
          res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
          res.end(bundleSrc);
          return;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  root: '.',
  publicDir: false,

  // JSX → Preact via esbuild's automatic runtime (`preact/jsx-runtime`).
  // Using esbuild config instead of `@preact/preset-vite` because the .xdc
  // bundle is built by an inline `build()` call (see `bundleEsmDev` above
  // and the `rollupOptions` in `build` below) with `configFile: false`,
  // which doesn't pick up plugins from this config.  HMR / debug-name
  // niceties from the preset aren't needed in the webxdc target anyway.
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'preact',
  },

  server: {
    port: 3000,
    open: false,
  },

  preview: {
    port: 3000,
  },

  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // Tree-shaking and minification (esbuild) come for free from Rollup
    // + Vite defaults — set them explicitly so the .xdc artifact never
    // accidentally regresses to an unminified bundle if a future Vite
    // major flips a default.
    minify: 'esbuild',
    // Sourcemaps in dev/test (.xdc files attached to PRs); stripped from
    // release artifacts to keep tag-built .xdc bytes lean and avoid
    // shipping original-source paths to end users.  Gated via
    // BUILD_RELEASE=1 (set by .github/workflows/test.yml on tag builds).
    sourcemap: !isRelease,
    // Default is 4096; pin it so the threshold for inlining small icons
    // / fonts vs. shipping them as separate dist/ files is visible in
    // config rather than implicit in Vite version bumps.
    assetsInlineLimit: 4096,
    // Vite's default 500 kB warning fires noisily on every build at the
    // current ~1.1 MB minified bundle.  webxdc apps load once from local
    // storage; HTTP-request elimination via code-splitting wouldn't help
    // (every chunk just becomes another file inside the .xdc).  See #192
    // "Out of scope".  Raise the threshold to 1500 kB so the warning
    // resurfaces only if the bundle grows past where re-evaluating the
    // single-chunk decision actually makes sense.
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      input: 'scripts/esm-entry.js',
      output: {
        format: 'iife',
        name: '__DD',
        entryFileNames: 'scripts/esm-bundle.js',
      },
    },
  },

  plugins: [
    mockWebxdc(),
    bundleEsmDev(),
    viteStaticCopy({
      targets: [
        { src: 'index.html', dest: '' },
        { src: 'manifest.toml', dest: '' },
        { src: 'icon.png', dest: '' },
        { src: 'CREDITS.txt', dest: '' },
        { src: 'LICENSE.txt', dest: '' },
        { src: 'LICENSE-CODE.txt', dest: '' },
        { src: 'LICENSE-ASSETS.txt', dest: '' },
        // Vendor libs are loaded as plain `<script>` tags from index.html
        // and exposed as browser globals (window.jQuery, window.numeral, …)
        // the ESM bundle reads from globalThis.
        { src: 'vendor', dest: '' },
        // CSS files are minified per-file (esbuild) on the way into
        // dist/, but kept as four separate files matching the four
        // `<link>` tags in index.html — preserving cascade order
        // without touching index.html or scripts/esm-entry.ts.
        // The glob matches `css/*.css`; with `dest: ''` the relative
        // path (css/foo.css) lands at dist/css/foo.css, exactly where
        // index.html's `./css/foo.css` references resolve.
        { src: 'css/*.css', dest: '', transform: minifyCssTransform },
        { src: 'img', dest: '' },
        // Ship only the fonts referenced from CSS; BowlbyOne.ttf and
        // BowlbyOneSC.ttf are unused (the .woff is loaded instead).
        { src: 'font/BowlbyOneSC.woff', dest: '' },
        { src: 'font/Voltaire-Regular.ttf', dest: '' },
        { src: 'font/Skranji-Regular.ttf', dest: '' },
        { src: 'font/SourceSansPro-Black.woff', dest: '' },
        { src: 'font/LICENSE', dest: '' },
        // views/*.html templates are now `?raw`-imported and bundled
        // into esm-bundle.js; the directory itself is no longer shipped.
        { src: 'data', dest: '' },
        { src: 'i18n', dest: '' },
      ],
    }),
    swapInCasualAssets(),
    minifyStaticJson(),
    buildXDC({ inDir: 'dist', outDir: '.', outFileName: `data-dealer-${variant}.xdc` }),
  ],
});
